### ISSUE TITLE
2015-02-17 Aグループ

### ISSUE THREAD

**Issue by rishibashival** [ValLaboratory/perfect_rails#101]
石橋亮
相坂麻衣
鈴木隼人
添田悠央
茂木友哉

**Comment by rishibashival** [comment]
石橋亮
相坂麻衣
鈴木隼人
添田悠央
茂木友哉

**Comment by soe-j** [comment]
@aisaka さんは外出でし

**Comment by TMogi** [comment]
minitest?なにそれおいしいの？

**Comment by soe-j** [comment]
トリプルH #とは

**Comment by soe-j** [comment]
正解はDHH

**Comment by soe-j** [comment]
DHHがrspec嫌いだからrailsデフォでは入らない

**Comment by soe-j** [comment]
minitestデフォで入るけど、ほとんど誰も使ったことない

**Comment by TMogi** [comment]
結論: rspec使おう

**Comment by soe-j** [comment]
もうrspecの話しかしない

**Comment by soe-j** [comment]
viewとかテストするにはcapybara

**Comment by TMogi** [comment]
今回はmodelのテストです

**Comment by soe-j** [comment]
capybaraはrspecの上で動きます

**Comment by soe-j** [comment]
「昨日Rspec使いました」
「テストをドリブンしたんですか？」
「いいえ後からです」

**Comment by soe-j** [comment]
describeとcontextとどう使い分ける？
実装は全く一緒なはず

**Comment by TMogi** [comment]
Rails4.1から自動でDB設定をロードしてくれて素敵

**Comment by soe-j** [comment]
schemaからロードしてくれるので、devでもmigrateしてないときはだめよ

**Comment by soe-j** [comment]
it #とは

**Comment by soe-j** [comment]
もともと it { should be_hogehoge } みたいな書き方が出来たので。
いまはshould非推奨

**Comment by TMogi** [comment]
cucumberは自然言語に近く書ける

**Comment by TMogi** [comment]
自然言語に近いは死亡フラグ

**Comment by soe-j** [comment]
目指すことは良いこと

**Comment by val00274** [comment]
遅れてすみません。合流します

**Comment by soe-j** [comment]
書籍通りのバージョンのrspecはちょっと困ることがあった

**Comment by soe-j** [comment]
letで宣言するのとbeforeで変数宣言するのとどっち使う？

**Comment by TMogi** [comment]
リスト7.2 RSpec風のminitestサンプル
<h1>紛らわしい！</h1>

**Comment by soe-j** [comment]
letでいってるメモ化 #とは
１回関数を実行して、その結果を保持しておくこと？
memoize

**Comment by soe-j** [comment]
めもいず

**Comment by soe-j** [comment]
テストでbeforeとかletでレコード作ると消えないから、テスト実行２回目がこけたりして困る

**Comment by soe-j** [comment]
shouldaべんり

**Comment by soe-j** [comment]
activemodelでも使える？かな？
チャリさんが後で試すそうです

**Comment by soe-j** [comment]
`it { should validate_length_of(:name).is_at_most(50) }`
は50文字はOK、51文字はダメっていうテストをやってくれてるってことでいいんだよね

**Comment by TMogi** [comment]
shoulda抹茶一覧
http://morizyun.github.io/blog/shoulda-matchers-rspec-matcher/

**Comment by TMogi** [comment]
メンバーが全員男性なのでfactory_girlには触れない(違

**Comment by soe-j** [comment]
factory girlなかなかできるやつ

**Comment by soe-j** [comment]
event作るときにuserが必要だから....っていうのもセットしとけばやっといてくれる最高

**Comment by TMogi** [comment]
こんな感じになります
↓
<h1>エラー！！</h1>
↓
恥ずかしい

**Comment by o-sawa** [comment]
もうマージされているようなのでクローズします
