### ISSUE TITLE
2015-02-17 Bグループ

### ISSUE THREAD

**Issue by rishibashival** [ValLaboratory/perfect_rails#102]
鈴木省吾
今井信夫
大澤有美
中野真理
佐藤昭彦

**Comment by rishibashival** [comment]
鈴木省吾
今井信夫
大澤有美
中野真理
佐藤昭彦

**Comment by o-sawa** [comment]
私書記なので発表はどなたかよろしくお願いしますー

**Comment by n-imai** [comment]
インストールでこける？

**Comment by nakano348** [comment]
いつもgemは新しいバージョンのものを入れてしまいます。

**Comment by o-sawa** [comment]
rspecの3.0.0に何か問題があるようなので、
皆さん 3.1.0 とか 3.2.0 とか入れてやっていますです( ˘ω˘)

**Comment by nakano348** [comment]
＿人人人人人人人人人人人人＿
＞　組み合わせが合わない　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣

**Comment by n-imai** [comment]
ネットの情報で3.0.0がコケるときは、3.0.2を入れろと書いてあったので、
入れたけど、その先のテスト実行時に駄目だった...

**Comment by e-fkmt** [comment]
Ginza.rbに参加できなかった上に本忘れた上やつがお邪魔してます

**Comment by nakano348** [comment]
`rails g rspec:install`
便利です。

**Comment by ssusan** [comment]
正直rspecの記法はあんまり好きじゃないｗ

**Comment by ssusan** [comment]
BDD推奨の流れ的にはrspecがそれを体現してる的な感じでしたっけ？

**Comment by e-fkmt** [comment]
本がないからやりたい放題喋ってる

**Comment by ssusan** [comment]
shoulda = should have
しらんがな！

**Comment by nakano348** [comment]
matcher → マッチャ…？

**Comment by e-fkmt** [comment]
マッチャかわいい :tea:

**Comment by o-sawa** [comment]
rspec-rails の 3.2.0 は記法が変わっているのでちょっと注意(書く分には前の記法も使えるよ)

**Comment by e-fkmt** [comment]
本の記法と違って何がなんだか分からなかった
（私はrspec 3.1.0を使いました）

**Comment by ssusan** [comment]
spec_helperだけじゃなくて、rails_helperが登場
rails_helperの中でspec_helperをrequireしている

**Comment by ssusan** [comment]
p252のspec_helperに記述を追加する箇所は、rails_helperに書くようにしましょう

**Comment by e-fkmt** [comment]
factoryGirl、短くかけますよのオプション（config.include FactoryGirl::Syntax::Methods）
書いたけどエラーが出て動きませんでした

**Comment by nakano348** [comment]
FactoryGirlの初期設定が難しいです（小並感）

**Comment by e-fkmt** [comment]
rails_helperに記述したら動きました！！！！ :beer: :beers: :beers: :beer:

**Comment by n-imai** [comment]
テスト終了時に、test.sqlite3の中を空にする？

**Comment by e-fkmt** [comment]
spec_helperとrails_helperが何がなんだか...何がどう違うのなんで分けられているの

**Comment by ssusan** [comment]
letはrspecのメソッド？

**Comment by ssusan** [comment]
こいつ結局なんなの感が

**Comment by ssusan** [comment]
letの引数で渡したシンボルを名前とする関数を定義して、その中身はブロックの内容で、評価されるのは関数呼び出し時ってことでいいのかな？

**Comment by o-sawa** [comment]
ちょっと古いけれど

すごいぞRSpec(letとlet!編)
http://d.hatena.ne.jp/yohfee/20110223/1298467548

>要するにメモ化するわけで、同一サンプル内だと同じオブジェクトを使いまわせるのだな。違うサンプルでは改めて評価される。さらに遅延評価なので実際に評価されるのは最初にメソッドが呼ばれたときだ。

うえぇえええ

**Comment by ssusan** [comment]
ああそうかメモ化するんだった

**Comment by o-sawa** [comment]
次回は
範囲：7-5 ~ 7-7終わるまで
ファシリ： @sussan さん
レポータ： @rishibashival さん

**Comment by o-sawa** [comment]
もうマージされているようなのでクローズします
