### ISSUE TITLE
2015-03-24 Aグループ

### ISSUE THREAD

**Issue by ieda** [ValLaboratory/perfect_rails#114]
※参加メンバー更新に伴い変更しました
家田、茂木、今井、相坂

**Comment by ieda** [comment]
vagrant使ってます x3.5

**Comment by TMogi** [comment]
windowsでlinux環境使いたいときに便利

**Comment by ieda** [comment]
ラベル付けあざーす

**Comment by TMogi** [comment]
Cygwin…(ﾎﾞｿｯ

**Comment by TMogi** [comment]
ホワイトボード投入

**Comment by TMogi** [comment]
BerksfileはbundlerのGemfileみたいなもの？

**Comment by TMogi** [comment]
berkshelfは闇が深い

+ (berkshelf経由で)すんなりインストールできない
+ 本家のデータが古いことが多い
+ chef 12.0以上対応のメソッドでハマる
+ なんでハマったか分かりにくい

**Comment by ieda** [comment]
api.berkshelf.com のデータが古い

**Comment by TMogi** [comment]
berkshelfを使うかpackageコマンドを使うか悩む

**Comment by ieda** [comment]
packageはシステム依存が多い

**Comment by ieda** [comment]
基本は公式参照、古かったらfork先、それでも古かったら自分でfork

**Comment by TMogi** [comment]
他のサーバ構成管理ツールは？

+ puppet
+ ANSIBLE
+ solt
+ AWS opsworks(chef)

**Comment by o-sawa** [comment]
@aisaka さん記述のホワイトボード
![2015-03-24 18 33 37](https://cloud.githubusercontent.com/assets/3654955/6799133/a22ce730-d256-11e4-8d3f-4bf38cfe1525.jpg)

**Comment by o-sawa** [comment]
もうマージされているようなのでクローズします
