### ISSUE TITLE
2015-03-24 Bグループ

### ISSUE THREAD

**Issue by ieda** [ValLaboratory/perfect_rails#115]
※参加メンバー更新に伴い変更しました
福本、添田、大澤、鈴木

**Comment by o-sawa** [comment]
DevOps のはなしー

**Comment by e-fkmt** [comment]
DevOps#どうですか

**Comment by ssusan** [comment]
自分はあんまりそこが問題になるようなプロダクトに関わったことないので実感としてはよくわからない

**Comment by e-fkmt** [comment]
コモディ化#とは

**Comment by soe-j** [comment]
ひとりでdevとopsやってるというのはあるかもしれない（devopsではない感）

**Comment by o-sawa** [comment]
綴りは commodity ?

**Comment by e-fkmt** [comment]
>市場参入時には高付加価値を持っていた商品が、普及段階における後発品との競争のなかで、その機能の優位性や特異性を失い、一般消費財のように定着していくこと。 消費者サイドから見ると、「どのメーカーを選んでも大差ない、いつでも手軽に購入できる商品」がコモディティー化された商品ということになる。

**Comment by ssusan** [comment]
要は普通になったってことかな

**Comment by o-sawa** [comment]
p277 のコラム
＿人人人人人人人人人人人人人＿
＞　Windows 終了のお知らせ　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣

**Comment by soe-j** [comment]
berksfile

**Comment by soe-j** [comment]
berk: ばか、まぬけ

**Comment by soe-j** [comment]
？！？？？！！

**Comment by ssusan** [comment]
Vagrant : 環境立ち上げるときのVMの設定とか構成管理とかをコマンドでよしなにしてくれるツール

でいい？

**Comment by soe-j** [comment]
そうです（たぶん、だいたい、ほぼ）

**Comment by soe-j** [comment]
Vagrantfileに書いとくと、そのとおりに設定してくれる

**Comment by soe-j** [comment]
vmの設定どっちがhostでguest？？

**Comment by soe-j** [comment]
guestがUbuntu
hostがmac

**Comment by ssusan** [comment]
guestが立ち上げたVM
hostがVMを立ち上げる側

**Comment by soe-j** [comment]
vagrant provisionっていつ使うの

**Comment by soe-j** [comment]
vagrant up は provision を含む
vagrant reload は stop, startするだけ？っぽい？

**Comment by ssusan** [comment]
プロビジョニング : 準備とか供給
要するにサーバの構成をする作業のことでいいのかな？

**Comment by soe-j** [comment]
vagrant reloadはconfigを読み直すが、
config.vm.provisionを設定した時はprovisionで反映される

**Comment by soe-j** [comment]
なぜUbuntu

**Comment by ssusan** [comment]
http://www.aerialline.com/comics/ubunchu

**Comment by o-sawa** [comment]
vagrant up の時 provision やってくれるのは、初回のみ
それ以外のとき(vagrant halt; vagrant up; した時とか、 vagrant reload した時とか) は、 provision はやってくれない。

**Comment by o-sawa** [comment]
もうマージされているようなのでクローズします
