### ISSUE TITLE
2015-06-02

### ISSUE THREAD

**Issue by TMogi** [ValLaboratory/perfect_rails#135]
本日5人なので1班です。

**Comment by TMogi** [comment]
範囲 : 9-4 ~ 9-5 (p353 - p370)﻿

**Comment by o-sawa** [comment]
今日は値オブジェクト

**Comment by val00274** [comment]
Entity, ValueObject：DDDの用語っすね

**Comment by ssusan** [comment]
今のプロジェクトでまさにエンティティ的な話が出てる

**Comment by TMogi** [comment]
うっかりなんでも文字列にしてしまいがち
でも良くないよね

**Comment by o-sawa** [comment]
composed_of 便利だよね

mapping には ２次元配列 で カラム名、値オブジェクトのメソッド名を渡してあげる

**Comment by o-sawa** [comment]
カラム名と値オブジェクトのメソッド名が同じだから例としてわかりにくかった感

**Comment by TMogi** [comment]
`composed_of` を使用するとカラム名が異なってもマッピングできる

**Comment by val00274** [comment]
Lispのコード見てるみたい

> mapping には ２次元配列 で カラム名、値オブジェクトのメソッド名を渡してあげる

**Comment by val00274** [comment]
`%w(a b c)` == `["a", "b", "c"]`

**Comment by o-sawa** [comment]
状況次第で composed_of 使ったり自分でメソッド定義したり使い分けましょう。とのこと。

**Comment by o-sawa** [comment]
9-5 Concern

**Comment by TMogi** [comment]
`Concern` はRails4から

**Comment by ssusan** [comment]
DBのテーブルとは直結しない概念をmoduleとして切り出す

**Comment by o-sawa** [comment]
ビジネスロジックか

**Comment by o-sawa** [comment]
感心事
横断的感心事

**Comment by TMogi** [comment]
無理に日本語訳した感

**Comment by val00274** [comment]
じゃあConcernって呼ぼう

**Comment by o-sawa** [comment]
ActiveSupport::Concern
included のやつは、簡潔になって感覚的に書けるようになったかな

**Comment by val00274** [comment]
Concernは横断的関心事に特化してるのか、そうでもないのか読んでて判断つかなかった

**Comment by val00274** [comment]
作法がわからん

**Comment by o-sawa** [comment]
横断的なものを書きやすくしてくれているけれど、横断的なものじゃなくてもいいんじゃないかなって感じがしました

**Comment by ssusan** [comment]
Concernと言うけど、内状は便利機能の集合って印象なので、気をつけないと何にでも使えちゃいそう。

**Comment by val00274** [comment]
p.368
concerningの例を見ると、Model内に直接書いてるということは使い回しのことは考えてない。
やはり横断的でなくても関心事にあたるものはConcernにして良さそう

**Comment by val00274** [comment]
"concerningの意義"の項を参照

**Comment by o-sawa** [comment]
concerning 使えばインラインモジュールが小さい記述で書けてかつ読みやすくなるのかなー

**Comment by o-sawa** [comment]
ルーティングがDRYに定義できるようになったのは便利そう

**Comment by o-sawa** [comment]
来週の範囲 : 9-6 ~ 9-7 (p370 ~ p375)
※ 区切りが悪いので 9章終わりまでですが、次が15ページ弱なので予習はもっとやっておくといいと思います
ファシリ: @ssusan 
レポータ: @TMogi

**Comment by TMogi** [comment]
マージしたのでcloseします。
