### ISSUE TITLE
2015-06-09

### ISSUE THREAD

**Issue by ssusan** [ValLaboratory/perfect_rails#136]
3人だけだと！

**Comment by ssusan** [comment]
今日は9-6と9-7

**Comment by n-imai** [comment]
よろしくおねがいしまーす　わーパチパチ

**Comment by n-imai** [comment]
サービスクラスは基本的に状態を持たない

**Comment by n-imai** [comment]
サービスクラスはモデルからロジックを抜き出したもの？

**Comment by TMogi** [comment]
遅れました

**Comment by TMogi** [comment]
`app/service` を自分で作成する
モデルやビューと平行に置く

**Comment by TMogi** [comment]
rubyの場合 `+` などもメソッドとして定義できる

```
def +(other)
  # 処理
end
```

**Comment by TMogi** [comment]
言語によって演算子の仕様が違うので注意

**Comment by TMogi** [comment]
パスを通さなくても良いように `autoload_path` を追加する

**Comment by TMogi** [comment]
サービスクラスは何にでも使用できるので濫用するのは危険

**Comment by ssusan** [comment]
Concernとはどう違うんだ？

**Comment by ssusan** [comment]
ConcernはいろんなModelに共通する処理をまとめたものって感じ？

**Comment by n-imai** [comment]
横断的関心事

**Comment by e-fkmt** [comment]
参戦（予習したとはいっていない）

**Comment by ssusan** [comment]
Serviceに分類するようなものも結局Modelなのでは感があってよくわからない。

**Comment by ssusan** [comment]
RailsのModelが、RDBのテーブルと1対1対応した概念なので、serviceという層を設けているのかな？

**Comment by ssusan** [comment]
なんでもかんでもModelの仕事にしていくと、どんどん肥大化していく。
関心の分離もできない。

**Comment by ssusan** [comment]
2種類以上のModelが関わってくると、そもそも何かのModelのクラスメソッドにするのも不自然だし。

**Comment by TMogi** [comment]
あと2回で終わり！

**Comment by e-fkmt** [comment]
分からないなりに目を通していて良かった
@ssusanさんの説明でなんとなくイメージつきました！ :sushi:

**Comment by e-fkmt** [comment]
>typeというカラム名があるとActiveRecodeは勝手にSTIであると判定してしまうので、typeというカラム名をその他の目的で利用しないように注意しておきましょう

うわぁあああ、私が開発合宿でガチハマりしたやつですwwwwww

**Comment by n-imai** [comment]
6/16(火)
10-1、10-2
P.376~P.391
ファシリ：今井
リポーター：福本

**Comment by e-fkmt** [comment]
カラム名をtypeとしてしまったときの対処法これです
http://qiita.com/ryonext/items/1a813639ab2a2a00058e
