### ISSUE TITLE
2015-06-23

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/perfect_rails#142]
最終回なので1班で！

**Comment by aisaka** [comment]
@ssusan 「そーするのかー」（小並感）

**Comment by aisaka** [comment]
https://www.ruby-toolbox.com/search?utf8=%E2%9C%93&q=railtie

**Comment by aisaka** [comment]
http://www.engineyard.co.jp/blog/2013/extending-rails-3-with-railties/

**Comment by soe-j** [comment]
「○○-railsつくればいんじゃね」
『○○でいんじゃね』
「ですね」

**Comment by aisaka** [comment]
うちの商材を利用する汎用画面みたいなのが xx-rails としてあるとおもしろいかもね

**Comment by aisaka** [comment]
http://qiita.com/kidach1/items/565c2c077ae8d15fe3a8

**Comment by aisaka** [comment]
http://activeadmin.info/

**Comment by aisaka** [comment]
https://github.com/plataformatec/devise

**Comment by aisaka** [comment]
Engineぐぐりにくそう

**Comment by soe-j** [comment]
実況忘れてた

**Comment by TMogi** [comment]
消してええええ Railtieしてええええ

**Comment by e-fkmt** [comment]
実況できてなかった

**Comment by soe-j** [comment]
リライトですね

**Comment by aisaka** [comment]
あっはい

**Comment by soe-j** [comment]
アジカンですね

**Comment by TMogi** [comment]
すいませんでした

**Comment by soe-j** [comment]
namespaceがわからなくてなにもわからない

**Comment by ssusan** [comment]
だめだーRails力が低くてさっぱりわかんねー

**Comment by aisaka** [comment]
なんか特定のものに名前を与えるみたいな印象？だけど詳しいことはわかりません

**Comment by soe-j** [comment]
さっぱりわからない(ええ声で)

**Comment by aisaka** [comment]
https://rubymonk.com/learning/books/1-ruby-primer/chapters/35-modules/lessons/80-modules-as-namespaces

**Comment by aisaka** [comment]
![](http://up.gc-img.net/post_img/2013/03/FiKrJx65KrRgwlE_sXOOV_31.jpeg)

**Comment by soe-j** [comment]
![JS Girls:rhino](http://tomo-e.github.io/js-girls/images/05.png)

**Comment by soe-j** [comment]
![JS Girls:ok](http://tomo-e.github.io/js-girls/images/09.png)

**Comment by e-fkmt** [comment]
![JS Girls:no](http://tomo-e.github.io/js-girls/images/10.png)

**Comment by aisaka** [comment]
みんなLTTMつかってる

**Comment by TMogi** [comment]
(どうやってレポートまとめるんだろう)

**Comment by e-fkmt** [comment]
最終回なのにgdgdしてる

**Comment by soe-j** [comment]
LTTM便利ですよね

**Comment by soe-j** [comment]
engine

**Comment by soe-j** [comment]
Mountable Engineはもっと独立してる

**Comment by e-fkmt** [comment]
いつかコントリパイセンになりたい

**Comment by soe-j** [comment]
単独でRailsアプリとして動く

**Comment by e-fkmt** [comment]
Railsとかじゃなくてもいいから

**Comment by aisaka** [comment]
Railtie: プラグインベース
Engine: Railtieがベースで、Railsのディレクトリ構成とかを使ってそれっぽいプラグインをつくる(雑)
Mountable Engine: 単体でWebアプリとして動くプラグインをつくる(ex. ActiveAdmin)

**Comment by nakano348** [comment]
gemはいつか作ってみたいものの、何を作るべきかわからないです

**Comment by soe-j** [comment]
駅名のmockとか出せたら....
長い駅名とか.....
リゾートゲートウェイ・ステーション駅とか.....
ステーション駅.....

**Comment by soe-j** [comment]
「とっととつくって、つよいひとたちにつくってもらえばいいんだよ」

**Comment by TMogi** [comment]
さっさとつくって、っょぃ人たちに直してもらう

**Comment by e-fkmt** [comment]
＿人人人人人人人＿
＞　終わりです　＜
￣Y^Y^Y^Y^Y^Y￣

**Comment by soe-j** [comment]
＿人人人人人人人＿
＞　終わりです　＜
￣Y^Y^Y^Y^Y^Y￣

**Comment by o-sawa** [comment]
＿人人人人人人人＿
＞　終わりです　＜
￣Y^Y^Y^Y^Y^Y￣
