### ISSUE TITLE
2015-01-06 Aグループ

### ISSUE THREAD

**Issue by t-furuya** [ValLaboratory/perfect_rails#77]
福井・中野・茂木・鈴木(省)

**Comment by fukui307** [comment]
ぜんぜんセマンティックなマークアップではない（どーん）

**Comment by TMogi** [comment]
前回に引き続きi18nの設定を忘れていた

**Comment by ssusan** [comment]
前回のが一部動いてないけどとりあえず進めてます

**Comment by fukui307** [comment]
Ruby だと `"`（ダブルクォーテーション）と `'`（シングルクォーテーション）にはそれぞれ意味がある。

* ダブルクォーテーション
  * バックスラッシュ記法OK
  * 式展開される
* シングルクォーテーション
  * バックスラッシュ記法NG
  * 式展開されない

**Comment by TMogi** [comment]
物理削除と論理削除がある
今回は物理削除

**Comment by fukui307** [comment]
論理削除用のgem...

**Comment by fukui307** [comment]
＿人人人人人人人人＿
＞　突然の過去編　＜
￣Y^Y^Y^Y^Y^Y^Y￣

**Comment by TMogi** [comment]
ユーザ消したらイベントはどうなるの？

**Comment by fukui307** [comment]
183ページ

> owner_idカラムにnullを許可しているのは、「6-8 退会機能を作る」で退会機能を実装する際にnullを保存するためです。

**Comment by fukui307** [comment]
イベントは残ってもいいのよ

**Comment by nakano348** [comment]
ユーザーが消えてもイベントは残る!!

**Comment by ssusan** [comment]
htmlでdata-confirmって属性でアラート出るんだ知らなかった

**Comment by ssusan** [comment]
あちがう、Railsのか

**Comment by fukui307** [comment]
data-*** は独自の属性です〜

※参考
http://www.html5.jp/tag/attributes/data.html

**Comment by fukui307** [comment]
HTML5からでした > 独自データ属性

**Comment by ssusan** [comment]
なるほどなるほど

**Comment by fukui307** [comment]
Bootstrapのモーダルウィンドウ使いたいときはどうするのでしょうか

**Comment by nakano348** [comment]
[こちらのリポジトリ](https://github.com/bluerail/twitter-bootstrap-rails-confirm)が関係ありそうです

**Comment by ssusan** [comment]
data-confirmは、jquery-ujs.jsで動作が書かれている

**Comment by fukui307** [comment]
（ちなみに独自データ属性は、jQueryMobileとかでもよくつかわれています！）

**Comment by t-furuya** [comment]
レポートマージしたのでクローズします
![寿司ゆき:good_night](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/79.png)
