### ISSUE TITLE
2015-01-06 Bグループ

### ISSUE THREAD

**Issue by t-furuya** [ValLaboratory/perfect_rails#78]
石橋・大澤・福本・鈴木(隼)

**Comment by e-fkmt** [comment]
ソース、何を追加したら良いか分からなかった

**Comment by o-sawa** [comment]
p197の リスト6.32 どこ直すのコレどこってなった
危うく全部書き直すところだった

**Comment by e-fkmt** [comment]
divの数合わないなと思ったら色々見落としてた

**Comment by chari270** [comment]
erbとメソッドって普通どっちから書くもんかね？
まぁ、にわとりたまごかね？

**Comment by rishibashival** [comment]
RESTful駆動感が強いか否かとか？

**Comment by e-fkmt** [comment]
蛇足ですが
「イベントを編集する」ボタンと「イベントを削除する」ボタンが同じ大きさで並んであるのがちょっともやっとする。そして削除の方が目立つ

**Comment by chari270** [comment]
htmlタグで書くのとヘルパー使うのどっちが主流なんですかね

**Comment by chari270** [comment]
複数人同時にアクセスして、先に誰かが消しちゃったりしたときって、6.37のところで落ちたりするんですかね？

**Comment by o-sawa** [comment]
findがidあること前提のものなのでエラーになりますねー

```
Couldn't find Event with 'id'=8 [WHERE "events"."owner_id" = ?]
```

**Comment by fukui307** [comment]
> プログラム側で生成する場合は、特に問題ない場合はHTMLタグヘルパーを使った方がいいかもしれません。が、タグヘルパーでは難しそうな場合はタグを生成してもいいでしょう。
> 
> ただし、一般に公開されるWebサイトでHTMLを生成する場合は、XSSなどのセキュリティに気をつけてください。

http://takahashim.hatenablog.jp/entry/2014/12/02/050540

**Comment by t-furuya** [comment]
レポートマージしたのでクローズします
![寿司ゆき:good_night](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/79.png)
