### ISSUE TITLE
2015-01-06 Cグループ

### ISSUE THREAD

**Issue by t-furuya** [ValLaboratory/perfect_rails#79]
家田・古谷・添田・今井(信)

**Comment by soe-j** [comment]
あけましておめでとうございます

**Comment by ieda** [comment]
soe-j: 色んな認証方法を認めているのに、p.197でtwitterへのリンクが含まれている件について

**Comment by t-furuya** [comment]
おくれてさーせん

**Comment by t-furuya** [comment]
話を早くするためじゃないでしょうか＞Twitter

**Comment by ieda** [comment]
link_to の data オプション引数の confirm キー 胸熱

**Comment by t-furuya** [comment]
http://www.html5.jp/tag/attributes/data.html
HTML5に独自データ属性というものがあってだな

**Comment by t-furuya** [comment]
ｺﾝﾌｧｰﾑ

**Comment by t-furuya** [comment]
独自データ属性はブラウザ側でよしなに動作してくれるそうです

**Comment by t-furuya** [comment]
そえだ氏のネタバレ

**Comment by t-furuya** [comment]
＼おわりです／

**Comment by t-furuya** [comment]
203〜215

**Comment by n-imai** [comment]
jquery_ujs.jsがよしなにやってくれている

**Comment by t-furuya** [comment]
1/13　
ファシリ：中野さん
リポーター：福井さん

**Comment by t-furuya** [comment]
レポートマージしたのでクローズします
![寿司ゆき:good_night](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/79.png)
