### ISSUE TITLE
2015-01-13 Aグループ

### ISSUE THREAD

**Issue by nakano348** [ValLaboratory/perfect_rails#81]
相坂・鈴木（省）・ 福本・今井（信）

**Comment by ssusan** [comment]
わからないなりにわかってきた by 今井さん

**Comment by ssusan** [comment]
CreateTicketsクラスのadd_indexが2つあるのは何？

**Comment by ssusan** [comment]
関連テーブルの場合、一方のカラムからもう一方のカラムへのインデックスみたいなものを、両方向分作るってことなんでしょうか？

**Comment by aisaka** [comment]
n+1問題っていう単語をはじめてしった(小並感)

**Comment by aisaka** [comment]
bullet: N+1起きてるところでこんなんだしてくれる

![](http://cdn-ak.f.st-hatena.com/images/fotolife/n/nipe880324/20141108/20141108134453.png)

**Comment by ssusan** [comment]
coffeescript部分は完全に写経した

**Comment by ssusan** [comment]
写経してるとクラス名やID名の打ち間違いでだいたいはまる

**Comment by aisaka** [comment]
ssusan「Webアプリケーションってつくるのたいへんだなー」

**Comment by ssusan** [comment]
やっぱり日本人、単数複数の区別がつらい

**Comment by e-fkmt** [comment]
前回の部分からエラーでて予習進んでない奴です\_(:3｣∠)\_

**Comment by ssusan** [comment]
Rails4.2で外部キー制約が付けられるように。
これで関連テーブルのマイグレーションファイル書くとどうなるだろう。

**Comment by ssusan** [comment]
マイグレーションファイルの変更とか削除とか今のなしとかやっぱりやりづらい

**Comment by ssusan** [comment]
erbでifやループを書く必要が出てくるとどんどんつらくなってくる

**Comment by e-fkmt** [comment]
erbが辛いという話
* if辛い
* どこのendか分からない
* ハイライトきかない

**Comment by ssusan** [comment]
erbやめればいいのかなっ

**Comment by nakano348** [comment]
レポートをマージしましたのでクローズいたします。
