### ISSUE TITLE
2015-01-13 Bグループ

### ISSUE THREAD

**Issue by nakano348** [ValLaboratory/perfect_rails#82]
福井・茂木・石橋・丸山

**Comment by fukui307** [comment]
もぎ：モーダルウィンドウにハマる

**Comment by TMogi** [comment]
modalをmodelと書いていて動かなかった間抜けは私です

**Comment by hmaruyama** [comment]
誤：model
正：modal

**Comment by fukui307** [comment]
そしてやはりHTML要素の扱いが私、気になります

**Comment by TMogi** [comment]
ポップアップはブラウザ寄り、モーダルはJS寄りでおk？

**Comment by fukui307** [comment]
モーダルウィンドウは見た目や挙動のカスタマイズ性がたかいです！

自作もできます。
参考：http://syncer.jp/jquery-modal-window

Bootstrapでは標準でモーダルウィンドウ用のJSとCSSが作られていますので、classを追加するだけでできちゃいます。べんり。

**Comment by hmaruyama** [comment]
コーヒースクリプトはインデントに注意！

**Comment by fukui307** [comment]
インデントは大事

**Comment by TMogi** [comment]
`forEach(message, i)` って書いたらエラーになった
`forEach (message, i)` ←正しくはforEachの後にスペースが必要

**Comment by fukui307** [comment]
CoffeeScript知らないと間違えて半角スペース消しちゃったり逆につけちゃったりしそうなので注意

**Comment by fukui307** [comment]
N+1問題 #とは

**Comment by fukui307** [comment]
![N+1問題 / Eager Loading とは](http://ruby-rails.hatenadiary.com/entry/20141108/1415418367)

**Comment by fukui307** [comment]
Kaminariつかお(´ー｀)

**Comment by nakano348** [comment]
レポートをマージしましたのでクローズいたします。
