### ISSUE TITLE
2015-01-13 Cグループ

### ISSUE THREAD

**Issue by nakano348** [ValLaboratory/perfect_rails#83]
大澤・添田・中野

**Comment by o-sawa** [comment]
みんな予習しようよっ！

**Comment by soe-j** [comment]
途中でモーダルウィンドウから送信ができなくてつみました

**Comment by o-sawa** [comment]
今回予習中に間違えたこと共有
* modalをmodelとよく書き間違いました
* 複数形にしなくていいところを複数形にしました
* div タグを dia タグにしてしまったりしました

**Comment by soe-j** [comment]
モーダル閉じなくても送信の結果DBに登録はできている....(なんでいま開発)

**Comment by soe-j** [comment]
p.204 リスト6.38のadd_index同じようなのやってるね

**Comment by soe-j** [comment]
user_idで探した中からevent_id探す時と
event_idで探した中からuser_id探すとき？

**Comment by nakano348** [comment]
Coffee Scriptがこわいです

**Comment by soe-j** [comment]
user_idの順番にしてそのなかでevent_idが順番になってる索引と
event_idの順番にしてそのなかでuser_idが順番になってる索引と

**Comment by soe-j** [comment]
ちょうど今回Coffee Scriptで問題起きてるっぽい！ひゃっはー！

**Comment by o-sawa** [comment]
p.215 の dependent: :destroy 超便利（小並感）

**Comment by soe-j** [comment]
jsのチェックならchromeの開発者ツールでエラー見れる

**Comment by soe-j** [comment]
find_by!はなかっときに例外出るやつでしたっけ

**Comment by nakano348** [comment]
「参加をキャンセルする」ということを、ロジックとしてはdeleteで表現するという発想がなかったです。
（「参加」という状態のものを削除する、という意味で納得しました。）

**Comment by soe-j** [comment]
`!` を検索できないくるしみ

**Comment by soe-j** [comment]
参加キャンセル＝ticket(参加表明)を削除する
すべてモノに落としこむ

**Comment by soe-j** [comment]
coffeescriptのエラーは
誤： `location reload()`
正： `location.reload()`
でした

**Comment by nakano348** [comment]
レポートをマージしましたのでクローズいたします。
