### ISSUE TITLE
2015-01-20 Aグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/perfect_rails#84]
@aisaka @rishibashival @nakano348

**Comment by aisaka** [comment]
p216 owner_idがnullに(戦慄)

**Comment by nakano348** [comment]
退会したユーザが作成したイベントのowner_idがnullになるのがもやもや

**Comment by nakano348** [comment]
NOT NULL 制約をかけなかったのはこの時のため…？！

**Comment by nakano348** [comment]
Railsとpadrinoのちがい

**Comment by nakano348** [comment]
Railsの方がドキュメントが多い

**Comment by aisaka** [comment]
自分なら論理削除にするなー感(遅)

論理削除：削除フラグをもっといてデータは残すタイプ
物理削除：レコード自体を削除

**Comment by nakano348** [comment]
`dependent:nullify`

**Comment by nakano348** [comment]
`nullify → ぬるる`

**Comment by nakano348** [comment]
dependent オプション便利すぎてこわいレベルですね

**Comment by aisaka** [comment]
before_action :authenticate 便利 (Sinatraだとだいたいbefore文起こすよね)
