### ISSUE TITLE
2015-01-20 Bグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/perfect_rails#85]
@ssusan @TMogi @e-fkmt

**Comment by TMogi** [comment]
ユーザが自分のアカウントだけなので色々と試しづらい

**Comment by TMogi** [comment]
@ssusan: アクションばっかり使ってたけど今回はretireを作ってやってる

**Comment by ssusan** [comment]
resoucesで自動的に作られるアクションばっかり使ってたけど、今回はretireを作ってやってる

**Comment by ssusan** [comment]
ファイナルアンサーの画面用のアクションを別途作ったため

**Comment by TMogi** [comment]
イベントを消したのに退会でエラーが出てしまった
原因がよく分からなかった

**Comment by TMogi** [comment]
rails cでEvent.delete_allとTicket.delete_allを実行したら退会できた

**Comment by ssusan** [comment]
前節(6-7)の最後の、Event削除時に依存するTicketを削除するのが抜けてたのが原因でした

**Comment by TMogi** [comment]
app/model/event.rb
×: `has_many :tickets`
○: `has_many :tickets, dependent: :destroy`

**Comment by TMogi** [comment]
前日夜中に突貫でやってくるの良くない

**Comment by TMogi** [comment]
@ssusanさんありがとうございます！

**Comment by ssusan** [comment]
`dependent: :nullify`とは

**Comment by ssusan** [comment]
ぬりふぁい

**Comment by TMogi** [comment]
ぬりふぁい

**Comment by e-fkmt** [comment]
私はいないものとして扱ってください :bow:

**Comment by e-fkmt** [comment]
私はいないものとして扱ってください :bow:

**Comment by ssusan** [comment]
削除時に関連するレコードのキーを削除する

**Comment by ssusan** [comment]
前節では`:destory`が入ってたけど、ここには他に何が入れられるのか

**Comment by TMogi** [comment]
p.220~
if文で分岐して退会したユーザを判断してるが
もう少し良い書き方できないだろうか？

**Comment by e-fkmt** [comment]
こっ...これはっ...中級者用です...（震え声）

**Comment by TMogi** [comment]
heler使えばスマートになるけど説明のためにベタ書きしている感
>分岐

**Comment by TMogi** [comment]
公式のActiverecordリファレンスがなかなか見つからない…？

**Comment by ssusan** [comment]
ActiveRecordのリファレンスどこ

**Comment by TMogi** [comment]
他の班の人がリンクを貼ってくれることを願う(投げやり)

**Comment by ssusan** [comment]
あったー
http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many

**Comment by ssusan** [comment]
`:dependent`には5種類設定できる模様

**Comment by TMogi** [comment]
頼れる先輩＠ssusanさん

**Comment by e-fkmt** [comment]
頼れる先輩@ssusanさん

**Comment by aisaka** [comment]
頼れる先輩@ssusanさん

**Comment by o-sawa** [comment]
頼れる先輩@ssusanさん

**Comment by ssusan** [comment]
( ﾟдﾟ )
