### ISSUE TITLE
2015-01-27 Bグループ

### ISSUE THREAD

**Issue by o-sawa** [ValLaboratory/perfect_rails#88]
@ssusan @hmaruyama @e-fkmt @soe-j

**Comment by soe-j** [comment]
予習しました？(進捗どうですかに代わるフレーズ)

**Comment by soe-j** [comment]
連続発表者記録を更新しそうです(回数はもうわからない)

**Comment by ssusan** [comment]
このアプリ用の404ページを作ってるけど、デフォでこういうページなかったっけ？

**Comment by soe-j** [comment]
デフォのページは/public/にいる気がする
production用だけ？

**Comment by ssusan** [comment]
`rescue_from`か、それに準ずるメソッドでデフォの404ページに飛ばせたりできる気はするけどよくわからない

**Comment by soe-j** [comment]
404だけわけといて、あとのエラーはサーバが悪かったり(5xx)するので通知とかすると良いかも

**Comment by ssusan** [comment]
`ActionController::RoutingError`が、最初`ActiveRecord`だと思ってエラーになった。
そしてあー`ActiveController`かーと思って直したらまたエラー、なんで……
…………`Active`じゃねえ`Action`だーーー！ってなった。

**Comment by ssusan** [comment]
kaminariは結構使ってるのかな

**Comment by soe-j** [comment]
kaminariはmamaspertでもお世話になっております

**Comment by soe-j** [comment]
リスト6.64
`@events`にいれてるとこ、前から評価してるとしたら、
10件のうちにwhereの条件外れるやつあったら１ページに9件とかになりそう

**Comment by soe-j** [comment]
p.48一番下からp.49
メソッドチェーンしてるとこの動作について
**実際にSQLの結果が必要になるまではDBにアクセスはしない**

**Comment by soe-j** [comment]
つまり、全部の条件を甘味してからSQLになげてる？
kaminariも最後にこっからここまでの10件ですってやってくれてるんじゃね

**Comment by soe-j** [comment]
ここでまた開始時間が過ぎてる罠

**Comment by soe-j** [comment]
ransackべんり！

**Comment by ssusan** [comment]
`cont`って何の略？

**Comment by ssusan** [comment]
predicateは、bool値を返す関数のこと

**Comment by ssusan** [comment]
「含む」なので`contain`説。なるほど。

**Comment by soe-j** [comment]
gteq:  grater than or equal

**Comment by e-fkmt** [comment]
今更参戦

**Comment by e-fkmt** [comment]
ransackべんり！（遅

**Comment by soe-j** [comment]
逆はlteqっぽい

**Comment by e-fkmt** [comment]
エラーハンドリングしたせいで、ガチエラーが出た時原因分からなくて一瞬困った（遅

**Comment by o-sawa** [comment]
レポートをマージしましたのでcloseします
![寿司ゆき:seeyou_kappamaki](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/51.png)
