### ISSUE TITLE
2015-2-3 Aグループ

### ISSUE THREAD

**Issue by e-fkmt** [ValLaboratory/perfect_rails#93]
@e-fkmt, @o-sawa , @ssusan, @TMogi

**Comment by e-fkmt** [comment]
予習してきた人「もちろんですよ〜！」

**Comment by e-fkmt** [comment]
試しに5000*5000のを上げたらちゃんと小さくなって感動した話

**Comment by ssusan** [comment]
画像のリサイズとかはImageMagicの機能。
それをラップしてRailsに使えるようにしたのがcarrierwaveかな？

**Comment by ssusan** [comment]
mini_magickの機能か

**Comment by o-sawa** [comment]
carrierwaveさんが、mini_magickさんやrmagickさんを使って小さくしてくれてるのかな
デフォルトでは入らないけど

**Comment by ssusan** [comment]
event_image_cacheの部分の動きがわからん

**Comment by e-fkmt** [comment]
その辺の件がいまいち分からなくてモヤモヤしてます

**Comment by o-sawa** [comment]
event_image_cacheのやつ、
　/public/uploads/tmp/ホニャホニャ/画像名
って感じのところにcacheされてる

**Comment by o-sawa** [comment]
cacheの期限は？

**Comment by o-sawa** [comment]
ちなみに普通にuploadした奴は、
  /public/uploads/event/event_image/イベントid/画像
ってところに保存されてる

**Comment by ssusan** [comment]
キャッシュ登録される状況で、そのまま記事作成しないで別ページに移動すると、キャッシュがそのまま残ってしまっているように見える

**Comment by ssusan** [comment]
これは自動で消えない？

**Comment by ssusan** [comment]
24時間経つと消える疑惑

**Comment by ssusan** [comment]
確かめられない

**Comment by o-sawa** [comment]
疑惑の元ファイル
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/cache.rb

**Comment by e-fkmt** [comment]
http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/Uploader/Cache/ClassMethods

**Comment by o-sawa** [comment]
自分でrake作ってcronで動かせってこと？

**Comment by e-fkmt** [comment]
くっ...

**Comment by o-sawa** [comment]
＿人人人人人人人＿
＞　分からない　＜
￣Y^Y^Y^Y^Y^Y￣

**Comment by ssusan** [comment]
自分で作るのかなあ

http://stackoverflow.com/questions/19126504/cleanup-tmp-directory-with-carrierwave

**Comment by ssusan** [comment]
明日試してみよう

**Comment by soe-j** [comment]
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/cache.rb#L44-L46
24時間
