### ISSUE TITLE
2015-2-3 Bグループ

### ISSUE THREAD

**Issue by e-fkmt** [ValLaboratory/perfect_rails#94]
@aisaka , @soe-j , @rishibashival , @n-imai

**Comment by aisaka** [comment]
Paperclip vs Carrierwave
http://blog.inouetakuya.info/entry/20131014/1381749488

**Comment by n-imai** [comment]
Paperclipの方が手軽で良さそう！！

**Comment by aisaka** [comment]
p232 event_image_cache 的な hidden_field でエラーハンドリングしてくれる

**Comment by n-imai** [comment]
cacheは悪さしないかな？？

**Comment by aisaka** [comment]
Cacheの挙動がわかんなくてさがしたら飯テロ
http://gin-palace.info/?p=27

**Comment by aisaka** [comment]
パラメータの中に画像を入れこむことができる(らしい)

**Comment by aisaka** [comment]
複数サーバ上で動かしている画像のハッシュ値とかが気になる木

**Comment by soe-j** [comment]
でもそれじゃないっぽいですね...

**Comment by aisaka** [comment]
https://github.com/carrierwaveuploader/carrierwave/blob/master/features/step_definitions/caching_steps.rb これなんだ？とおもったら
rspec-givenの書き方ぽい
http://qiita.com/kakkunpakkun/items/7b9c5a463cc7d0ba67a6

**Comment by aisaka** [comment]
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/mount.rb#L443

**Comment by aisaka** [comment]
~~~ruby
end # Extension
~~~
