### ISSUE TITLE
2015-02-10 Bグループ

### ISSUE THREAD

**Issue by soe-j** [ValLaboratory/perfect_rails#97]
@aisaka 相坂さん
@o-sawa 大澤さん
@TMogi 茂木さん
@soe-j 添田

**Comment by soe-j** [comment]
復讐だああああああ

**Comment by o-sawa** [comment]
みんなで２章を復習しましょう

**Comment by TMogi** [comment]
controllerはシンプルに

**Comment by soe-j** [comment]
Railsの動き

routes.rbでアクセスがどのコントローラを呼ぶか設定
ContorollerでModelとかいじったり、Viewで表示したい値とかを用意
Modelにロジックとか肝
Viewで表示

**Comment by soe-j** [comment]
6章まででconcern使わなかったなあ
9章で詳しく出てくるらしい

**Comment by TMogi** [comment]
Activerecordのjoinとか使ったことある人居ますか？

**Comment by TMogi** [comment]
SQL分かってないと書けないですね…

**Comment by soe-j** [comment]
メソッド使うことでSQLインジェクション避けになる

**Comment by TMogi** [comment]
MySQL viewとかActiverecordで書き直すとDB変えようとかなったときに幸せになれそう

**Comment by soe-j** [comment]
select文30行のプロジェクトとかあったらしい。（伝説のもの）

**Comment by soe-j** [comment]
モデルどんなの作ればいいのかとかわかりづらい

**Comment by soe-j** [comment]
既存のDBにつなぐのにrails g modelするとmigrationファイルできて、migrateしてねっていうのなんとかならないか

**Comment by o-sawa** [comment]
migrationをskipしてmodelをつくる
http://qiita.com/fukkyy/items/a054e24c8c38d0fe11ce

**Comment by soe-j** [comment]
(共有するときは参考が大事)

**Comment by soe-j** [comment]
has_manyとかnull制約とかはrailsだけの設定。DBはまっさらなので要注意

**Comment by soe-j** [comment]
外部キー制約は最新railsで付けれるようになった

**Comment by soe-j** [comment]
基本Railsでいじって、どうしても直でいじらなきゃいけないときのために制約きつめにしとくべきかも

**Comment by soe-j** [comment]
Rails上で書いて直でDBの制約つける設定はあるのか

**Comment by soe-j** [comment]
・migrationファイルの設定は全部DB直設定っぽい

**Comment by soe-j** [comment]
Modelファイルで制約かけてるのはRails上の設定
